### ISSUE TITLE
ninja问题

### ISSUE THREAD

**Issue by trra1988** [uyzhang/PCT_Pytorch#13]
请问一下这种情况该怎么解决，运行的时候报了这个错误，已经安装了ninja还是不可以

roup_points_gpu.cuda.o 
FAILED: group_points_gpu.cuda.o 
/usr/bin/nvcc --generate-dependencies-with-compile --dependency-output group_points_gpu.cuda.o.d -DTORCH_EXTENSION_NAME=_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/lin/program/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /home/lin/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_37,code=compute_37 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_62,code=sm_62 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -Xfatbin -compress-all -std=c++14 -c /home/lin/program/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/src/group_points_gpu.cu -o group_points_gpu.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
ninja: build stopped: subcommand failed.

**Comment by uyzhang** [comment]
#3 你可以看这个issue 重新编译一下

**Comment by trra1988** [comment]
> #3 你可以看这个issue 重新编译一下

我想尝试一下直接拷贝fps的代码，想再请问一下fps的代码是在哪里？谢谢

**Comment by trra1988** [comment]
> #3 你可以看这个issue 重新编译一下

我想尝试一下直接拷贝fps的代码，想再请问一下fps的代码是在哪里？谢谢

**Comment by uyzhang** [comment]
> > #3 你可以看这个issue 重新编译一下
> 
> 我想尝试一下直接拷贝fps的代码，想再请问一下fps的代码是在哪里？谢谢

https://github.com/uyzhang/PCT_Pytorch/blob/main/pointnet2_ops_lib/pointnet2_ops/pointnet2_utils.py

**Comment by trra1988** [comment]
> > > #3 你可以看这个issue 重新编译一下
> > 
> > 
> > 我想尝试一下直接拷贝fps的代码，想再请问一下fps的代码是在哪里？谢谢
> 
> https://github.com/uyzhang/PCT_Pytorch/blob/main/pointnet2_ops_lib/pointnet2_ops/pointnet2_utils.py

再请教一下，我已经将pointnet2_utils.py中的FurthestPointSampling类拷贝至util.py中，但是报错了
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from model import Pct
  File "/home/lin/program/PCT_Pytorch-main/model.py", line 4, in <module>
    from util import sample_and_group 
  File "/home/lin/program/PCT_Pytorch-main/util.py", line 24, in <module>
    _ext = load(
  File "/home/lin/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1079, in load
    return _jit_compile(
  File "/home/lin/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1292, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/lin/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1391, in _write_ninja_file_and_build_library
    _write_ninja_file_to_build_library(
  File "/home/lin/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1823, in _write_ninja_file_to_build_library
    _write_ninja_file(
  File "/home/lin/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1874, in _write_ninja_file
    assert len(sources) > 0
AssertionError
是不是拷贝错了，第一次使用python和c++一起编译，感谢

**Comment by uyzhang** [comment]
你可以直接from pointnet2_ops_lib.pointnet2_ops.pointnet2_utils import furthest_point_sample
然后把utils.py里面的
fps_idx = pointnet2_utils.furthest_point_sample(xyz, npoint).long() # [B, npoint]
改为
fps_idx = furthest_point_sample(xyz, npoint).long() # [B, npoint]   
应该就行了

**Comment by trra1988** [comment]
> 你可以直接from pointnet2_ops_lib.pointnet2_ops.pointnet2_utils import furthest_point_sample
> 然后把utils.py里面的
> fps_idx = pointnet2_utils.furthest_point_sample(xyz, npoint).long() # [B, npoint]
> 改为
> fps_idx = furthest_point_sample(xyz, npoint).long() # [B, npoint]
> 应该就行了

(base) lin@lin:~/PCT_Pytorch-main$ python main.py --exp_name=train --num_points=1024 --use_sgd=True --batch_size 32 --epochs 250 --lr 0.0001
/home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/pointnet2_utils.py:15: UserWarning: Unable to load pointnet2_ops cpp extension. JIT Compiling.
  warnings.warn("Unable to load pointnet2_ops cpp extension. JIT Compiling.")
Traceback (most recent call last):
  File "/home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/pointnet2_utils.py", line 8, in <module>
    import pointnet2_ops_lib.pointnet2_ops._ext as _ext
ModuleNotFoundError: No module named 'pointnet2_ops_lib.pointnet2_ops._ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lin/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1667, in _run_ninja_build
    subprocess.run(
  File "/home/lin/anaconda3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from model import Pct
  File "/home/lin/PCT_Pytorch-main/model.py", line 4, in <module>
    from util import sample_and_group 
  File "/home/lin/PCT_Pytorch-main/util.py", line 3, in <module>
    from pointnet2_ops_lib.pointnet2_ops.pointnet2_utils import FurthestPointSampling
  File "/home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/__init__.py", line 1, in <module>
    import pointnet2_ops_lib.pointnet2_ops.pointnet2_modules
  File "/home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/pointnet2_modules.py", line 6, in <module>
    from ..pointnet2_ops import pointnet2_utils
  File "/home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/pointnet2_utils.py", line 24, in <module>
    _ext = load(
  File "/home/lin/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1079, in load
    return _jit_compile(
  File "/home/lin/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1292, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/lin/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1404, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/lin/anaconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_ext': [1/5] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output sampling_gpu.cuda.o.d -DTORCH_EXTENSION_NAME=_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /home/lin/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_37,code=compute_37 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_62,code=sm_62 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -Xfatbin -compress-all -std=c++14 -c /home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/src/sampling_gpu.cu -o sampling_gpu.cuda.o 
FAILED: sampling_gpu.cuda.o 
/usr/bin/nvcc --generate-dependencies-with-compile --dependency-output sampling_gpu.cuda.o.d -DTORCH_EXTENSION_NAME=_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /home/lin/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_37,code=compute_37 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_62,code=sm_62 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -Xfatbin -compress-all -std=c++14 -c /home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/src/sampling_gpu.cu -o sampling_gpu.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
[2/5] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output interpolate_gpu.cuda.o.d -DTORCH_EXTENSION_NAME=_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /home/lin/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_37,code=compute_37 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_62,code=sm_62 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -Xfatbin -compress-all -std=c++14 -c /home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/src/interpolate_gpu.cu -o interpolate_gpu.cuda.o 
FAILED: interpolate_gpu.cuda.o 
/usr/bin/nvcc --generate-dependencies-with-compile --dependency-output interpolate_gpu.cuda.o.d -DTORCH_EXTENSION_NAME=_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /home/lin/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_37,code=compute_37 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_62,code=sm_62 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -Xfatbin -compress-all -std=c++14 -c /home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/src/interpolate_gpu.cu -o interpolate_gpu.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
[3/5] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output ball_query_gpu.cuda.o.d -DTORCH_EXTENSION_NAME=_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /home/lin/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_37,code=compute_37 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_62,code=sm_62 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -Xfatbin -compress-all -std=c++14 -c /home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/src/ball_query_gpu.cu -o ball_query_gpu.cuda.o 
FAILED: ball_query_gpu.cuda.o 
/usr/bin/nvcc --generate-dependencies-with-compile --dependency-output ball_query_gpu.cuda.o.d -DTORCH_EXTENSION_NAME=_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /home/lin/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_37,code=compute_37 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_62,code=sm_62 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -Xfatbin -compress-all -std=c++14 -c /home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/src/ball_query_gpu.cu -o ball_query_gpu.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
[4/5] /usr/bin/nvcc --generate-dependencies-with-compile --dependency-output group_points_gpu.cuda.o.d -DTORCH_EXTENSION_NAME=_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /home/lin/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_37,code=compute_37 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_62,code=sm_62 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -Xfatbin -compress-all -std=c++14 -c /home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/src/group_points_gpu.cu -o group_points_gpu.cuda.o 
FAILED: group_points_gpu.cuda.o 
/usr/bin/nvcc --generate-dependencies-with-compile --dependency-output group_points_gpu.cuda.o.d -DTORCH_EXTENSION_NAME=_ext -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/TH -isystem /home/lin/anaconda3/lib/python3.8/site-packages/torch/include/THC -isystem /home/lin/anaconda3/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_37,code=compute_37 -gencode=arch=compute_37,code=sm_37 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_62,code=sm_62 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' -O3 -Xfatbin -compress-all -std=c++14 -c /home/lin/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/_ext-src/src/group_points_gpu.cu -o group_points_gpu.cuda.o 
nvcc fatal   : Unknown option '-generate-dependencies-with-compile'
ninja: build stopped: subcommand failed.
报这个错误了，import pointnet2_ops_lib.pointnet2_ops._ext as _ext，请问一下_ext的文件在哪里？是_ext_src么？

**Comment by trra1988** [comment]
> 你可以直接from pointnet2_ops_lib.pointnet2_ops.pointnet2_utils import furthest_point_sample
> 然后把utils.py里面的
> fps_idx = pointnet2_utils.furthest_point_sample(xyz, npoint).long() # [B, npoint]
> 改为
> fps_idx = furthest_point_sample(xyz, npoint).long() # [B, npoint]
> 应该就行了

是不是跟cuda版本有关系？我是cuda11.3 对应pytorch1.8.1-cu111的

**Comment by uyzhang** [comment]
我刚试了一下，的确是有问题，我也没有试过直接粘fps的代码去运行，#3有人解决了这个问题，你可以发邮件联系他问详细操作

**Comment by uyzhang** [comment]
或者你可以参考pointnet2的官方repo去将这个代码编译成功，编译失败的问题，我觉得应该是环境配置的问题。

**Comment by trra1988** [comment]
> 或者你可以参考pointnet2的官方repo去将这个代码编译成功，编译失败的问题，我觉得应该是环境配置的问题。

好的，我再试一下谢谢
