### ISSUE TITLE
An error ocurred when running "pip install pointnet2_ops_lib/"

### ISSUE THREAD

**Issue by CaineGu** [uyzhang/PCT_Pytorch#3]
After ensuring all env is satisfied as intro given, a error occurred when running pip install pointnet2_ops_lib/.

then I get some as follow:

Requirement already satisfied: torch>=1.4 in /home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages (from pointnet2-ops==3.0.0) (1.7.1)
Requirement already satisfied: numpy in /home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages (from torch>=1.4->pointnet2-ops==3.0.0) (1.20.1)
Requirement already satisfied: typing-extensions in /home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages (from torch>=1.4->pointnet2-ops==3.0.0) (3.7.4.3)
Building wheels for collected packages: pointnet2-ops
  **_Building wheel for pointnet2-ops (setup.py) ... error
  ERROR: Command errored out with exit status 1:_**
   command: /home/caine/anaconda3/envs/pt1.6/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0rur_w6f/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0rur_w6f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-_sl18hkq
       cwd: /tmp/pip-req-build-0rur_w6f/
  Complete output (82 lines):
  running bdist_wheel
  /home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py:352: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
    warnings.warn(msg.format('we could not find ninja.'))
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/pointnet2_ops
  copying pointnet2_ops/__init__.py -> build/lib.linux-x86_64-3.7/pointnet2_ops
  copying pointnet2_ops/_version.py -> build/lib.linux-x86_64-3.7/pointnet2_ops
  copying pointnet2_ops/pointnet2_modules.py -> build/lib.linux-x86_64-3.7/pointnet2_ops
  copying pointnet2_ops/pointnet2_utils.py -> build/lib.linux-x86_64-3.7/pointnet2_ops
  running egg_info
  creating pointnet2_ops.egg-info
  writing pointnet2_ops.egg-info/PKG-INFO
  writing dependency_links to pointnet2_ops.egg-info/dependency_links.txt
  writing requirements to pointnet2_ops.egg-info/requires.txt
  writing top-level names to pointnet2_ops.egg-info/top_level.txt
  writing manifest file 'pointnet2_ops.egg-info/SOURCES.txt'
  reading manifest file 'pointnet2_ops.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'pointnet2_ops.egg-info/SOURCES.txt'
  creating build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src
  creating build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/include
  copying pointnet2_ops/_ext-src/include/ball_query.h -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/include
  copying pointnet2_ops/_ext-src/include/cuda_utils.h -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/include
  copying pointnet2_ops/_ext-src/include/group_points.h -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/include
  copying pointnet2_ops/_ext-src/include/interpolate.h -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/include
  copying pointnet2_ops/_ext-src/include/sampling.h -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/include
  copying pointnet2_ops/_ext-src/include/utils.h -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/include
  creating build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/ball_query.cpp -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/ball_query_gpu.cu -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/bindings.cpp -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/group_points.cpp -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/group_points_gpu.cu -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/interpolate.cpp -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/interpolate_gpu.cu -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/sampling.cpp -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
  copying pointnet2_ops/_ext-src/src/sampling_gpu.cu -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-0rur_w6f/setup.py", line 38, in <module>
      include_package_data=True,
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
      _build_ext.run(self)
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 361, in build_extensions
      self._check_abi()
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 696, in _check_abi
      check_compiler_abi_compatibility(compiler)
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 265, in check_compiler_abi_compatibility
      if not check_compiler_ok_for_platform(compiler):
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 225, in check_compiler_ok_for_platform
      which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/subprocess.py", line 411, in check_output
      **kwargs).stdout
    File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/subprocess.py", line 512, in run
      output=stdout, stderr=stderr)
  subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
  ----------------------------------------
  **_ERROR: Failed building wheel for pointnet2-ops
  Running setup.py clean for pointnet2-ops
Failed to build pointnet2-ops
Installing collected packages: pointnet2-ops
    Running setup.py install for pointnet2-ops ... error
    ERROR: Command errored out with exit status 1:_**
     command: /home/caine/anaconda3/envs/pt1.6/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0rur_w6f/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0rur_w6f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4xeyzhgj/install-record.txt --single-version-externally-managed --compile --install-headers /home/caine/anaconda3/envs/pt1.6/include/python3.7m/pointnet2-ops
         cwd: /tmp/pip-req-build-0rur_w6f/
    Complete output (82 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/pointnet2_ops
    copying pointnet2_ops/__init__.py -> build/lib.linux-x86_64-3.7/pointnet2_ops
    copying pointnet2_ops/_version.py -> build/lib.linux-x86_64-3.7/pointnet2_ops
    copying pointnet2_ops/pointnet2_modules.py -> build/lib.linux-x86_64-3.7/pointnet2_ops
    copying pointnet2_ops/pointnet2_utils.py -> build/lib.linux-x86_64-3.7/pointnet2_ops
    running egg_info
    writing pointnet2_ops.egg-info/PKG-INFO
    writing dependency_links to pointnet2_ops.egg-info/dependency_links.txt
    writing requirements to pointnet2_ops.egg-info/requires.txt
    writing top-level names to pointnet2_ops.egg-info/top_level.txt
    /home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py:352: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
      warnings.warn(msg.format('we could not find ninja.'))
    reading manifest file 'pointnet2_ops.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pointnet2_ops.egg-info/SOURCES.txt'
    creating build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src
    creating build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/include
    copying pointnet2_ops/_ext-src/include/ball_query.h -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/include
    copying pointnet2_ops/_ext-src/include/cuda_utils.h -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/include
    copying pointnet2_ops/_ext-src/include/group_points.h -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/include
    copying pointnet2_ops/_ext-src/include/interpolate.h -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/include
    copying pointnet2_ops/_ext-src/include/sampling.h -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/include
    copying pointnet2_ops/_ext-src/include/utils.h -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/include
    creating build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
    copying pointnet2_ops/_ext-src/src/ball_query.cpp -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
    copying pointnet2_ops/_ext-src/src/ball_query_gpu.cu -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
    copying pointnet2_ops/_ext-src/src/bindings.cpp -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
    copying pointnet2_ops/_ext-src/src/group_points.cpp -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
    copying pointnet2_ops/_ext-src/src/group_points_gpu.cu -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
    copying pointnet2_ops/_ext-src/src/interpolate.cpp -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
    copying pointnet2_ops/_ext-src/src/interpolate_gpu.cu -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
    copying pointnet2_ops/_ext-src/src/sampling.cpp -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
    copying pointnet2_ops/_ext-src/src/sampling_gpu.cu -> build/lib.linux-x86_64-3.7/pointnet2_ops/_ext-src/src
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-0rur_w6f/setup.py", line 38, in <module>
        include_package_data=True,
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 361, in build_extensions
        self._check_abi()
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 696, in _check_abi
        check_compiler_abi_compatibility(compiler)
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 265, in check_compiler_abi_compatibility
        if not check_compiler_ok_for_platform(compiler):
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 225, in check_compiler_ok_for_platform
        which = subprocess.check_output(['which', compiler], stderr=subprocess.STDOUT)
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/home/caine/anaconda3/envs/pt1.6/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['which', 'g++']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/caine/anaconda3/envs/pt1.6/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-0rur_w6f/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-0rur_w6f/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4xeyzhgj/install-record.txt --single-version-externally-managed --compile --install-headers /home/caine/anaconda3/envs/pt1.6/include/python3.7m/pointnet2-ops Check the logs for full command output.

what can i do then ?

**Comment by uyzhang** [comment]
The pointnet2_ops_lib is from https://github.com/erikwijmans/Pointnet2_PyTorch. You can find the detail of the installation in this repo.

**Comment by CaineGu** [comment]
> The pointnet2_ops_lib is from https://github.com/erikwijmans/Pointnet2_PyTorch. You can find the detail of the installation in this repo.
I have refer to pointnet2 detail, someone have same problem but haven't been solved yet

**Comment by pompeii222** [comment]
Only the FPS is used in pointnet2_ops_lib, you can import it without piping import pointnet2_ops_lib to accomplish training.

**Comment by swzaaaaaaa** [comment]
> Only the FPS is used in pointnet2_ops_lib, you can import it without piping import pointnet2_ops_lib to accomplish training.
直接将fps代码复制一下就可以了，不用编译了。

**Comment by uyzhang** [comment]
> > Only the FPS is used in pointnet2_ops_lib, you can import it without piping import pointnet2_ops_lib to accomplish training.
> > 直接将fps代码复制一下就可以了，不用编译了。

是的 如果实在编译不了 也可以这样

**Comment by trra1988** [comment]
> > Only the FPS is used in pointnet2_ops_lib, you can import it without piping import pointnet2_ops_lib to accomplish training.
> > 直接将fps代码复制一下就可以了，不用编译了。

请教一下，我尝试把pointnet2_utils拷贝到了util.py中，还是报编译错误，请问一下您是怎么操作的？谢谢

**Comment by pompeii222** [comment]
你直接把pointnet2_utils的FPS（最远点采样）的函数复制到util.py就好了

**Comment by sannnnnyss** [comment]
把pointnet2_utils的FPS（最远点采样）的函数复制到util.py之后，直接运行python main.py，出现no module named 'pointnet2_ops'怎么办？或者说中间还需要什么操作？

**Comment by sannnnnyss** [comment]
把pointnet2_utils的FPS（最远点采样）的函数复制到util.py之后，直接运行python main.py，出现no module named 'pointnet2_ops'怎么办？或者说中间还需要什么操作？

**Comment by caiya55** [comment]
Hi, @swzaaaaaaa ，我也遇到同样的问题了，复制过去没法实现了，因为里面的ext函数还是基于c++写的，所以我找到了纯python实现的代码，成功运行了，目前精度还未知，但作为代码的原理学习应该够用了。
```
def get_dists(points1, points2):
    '''
    Calculate dists between two group points
    :param cur_point: shape=(B, M, C)
    :param points: shape=(B, N, C)
    :return:
    '''
    B, M, C = points1.shape
    _, N, _ = points2.shape
    dists = torch.sum(torch.pow(points1, 2), dim=-1).view(B, M, 1) + \
            torch.sum(torch.pow(points2, 2), dim=-1).view(B, 1, N)
    dists -= 2 * torch.matmul(points1, points2.permute(0, 2, 1))
    dists = torch.where(dists < 0, torch.ones_like(dists) * 1e-7, dists) # Very Important for dist = 0.
    return torch.sqrt(dists).float()

def fps(xyz, M):
    '''
    Sample M points from points according to farthest point sampling (FPS) algorithm.
    :param xyz: shape=(B, N, 3)
    :return: inds: shape=(B, M)
    '''
    device = xyz.device
    B, N, C = xyz.shape
    centroids = torch.zeros(size=(B, M), dtype=torch.long).to(device)
    dists = torch.ones(B, N).to(device) * 1e5
    inds = torch.randint(0, N, size=(B, ), dtype=torch.long).to(device)
    batchlists = torch.arange(0, B, dtype=torch.long).to(device)
    for i in range(M):
        centroids[:, i] = inds
        cur_point = xyz[batchlists, inds, :] # (B, 3)
        cur_dist = torch.squeeze(get_dists(torch.unsqueeze(cur_point, 1), xyz))
        dists[cur_dist < dists] = cur_dist[cur_dist < dists]
        inds = torch.max(dists, dim=1)[1]
    return centroids
```

链接在这里：
https://zhuanlan.zhihu.com/p/234638980

**Comment by zsl4399** [comment]
> 你直接把pointnet2_utils的FPS（最远点采样）的函数复制到util.py就好了

你好，请问可以详细说一下具体怎么做吗，因为复制过去有很多参数需要修改，我改不通
