### ISSUE TITLE
ImportError: No module named '_ext'

### ISSUE THREAD

**Issue by zcxxlshirley** [uyzhang/PCT_Pytorch#4]
ModuleNotFoundError: No module named '_ext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 9, in <module>
    from model import Pct
  File "/home/cx/NewDisk/xxl/PCT_Pytorch-main/model.py", line 4, in <module>
    from util import sample_and_group 
  File "/home/cx/NewDisk/xxl/PCT_Pytorch-main/util.py", line 3, in <module>
    from pointnet2_ops_lib.pointnet2_ops import pointnet2_utils
  File "/home/cx/NewDisk/xxl/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/__init__.py", line 1, in <module>
    from . import pointnet2_modules
  File "/home/cx/NewDisk/xxl/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/pointnet2_modules.py", line 6, in <module>
    from . import pointnet2_utils
  File "/home/cx/NewDisk/xxl/PCT_Pytorch-main/pointnet2_ops_lib/pointnet2_ops/pointnet2_utils.py", line 30, in <module>
    with_cuda=True,
  File "/home/cx/NewDisk/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 661, in load
    is_python_module)
  File "/home/cx/NewDisk/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 841, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "/home/cx/NewDisk/anaconda3/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1048, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "/home/cx/NewDisk/anaconda3/lib/python3.6/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_ext'

**Comment by zcxxlshirley** [comment]
When debugging, the system prompts for the above error. I really didn't find '_ext' instead of '_ext-src'. How to address? Look forward to your reply!THX~~~

**Comment by comewei** [comment]
> When debugging, the system prompts for the above error. I really didn't find '_ext' instead of '_ext-src'. How to address? Look forward to your reply!THX~~~

hello,When I debug,I also meet the same question.do you sovle it. 
And, do you know what's the code means
`grouped_xyz = index_points(xyz, idx) # [B, npoint, nsample, C]
    grouped_xyz_norm = grouped_xyz - new_xyz.view(B, S, 1, C)
    grouped_points = index_points(points, idx)
    grouped_points_norm = grouped_points - new_points.view(B, S, 1, -1)`
I think the first and second codes is no effect. why does it appear?

**Comment by ANABUR920** [comment]
same problem
